"""delete schedule table

Revision ID: 86fc2302f33c
Revises: bda8ab57925c
Create Date: 2024-12-26 00:18:34.612886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '86fc2302f33c'
down_revision: Union[str, None] = 'bda8ab57925c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_schedule')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('end_time', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='event_schedule_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
