"""add new fields

Revision ID: efbac7da0e2a
Revises: 86fc2302f33c
Create Date: 2024-12-26 00:42:20.216246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'efbac7da0e2a'
down_revision: Union[str, None] = '86fc2302f33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'location',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.add_column('notification', sa.Column('image_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'image_url')
    op.alter_column('event', 'location',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
